{
 "title": "Ninjava",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Customer List Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "customer_list_time_seconds_max{}"
    }
   ]
  },
  {
   "title": "Report Generation Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "pageVisit_report_time_seconds_max{}"
    }
   ]
  },
  {
   "title": "Num. Reports Generated",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pageVisit_report_count_total{}" }
   ]
  },
  {
   "title": "Num. PageVisit  Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "increase(pageVisit_webhook_count_total{}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "PageVisit Webhook Process Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "pageVisit_webhook_time_seconds_max{}"
    }
   ]
  }
 ]
}